### ISSUE TITLE
  Interpreting payload data in Version 3 TTN

### ISSUE THREAD

**Issue by dslhias** [SodaqMoja/SodaqOne-UniversalTracker#4]
Hello,
i am trying to decode UniversalTracker V3  payloads that are received by: 
`mosquitto_sub -h staging.thethingsnetwork.org -t '+/devices/+/up' -u *********** -P '*************' -v`

The payload looks like that:
`LYNdn/wjVo54W5/4+EIMyn3USIrX`

Using **my** payload, the scripts offered in forum are failing:
http://forum.sodaq.com/t/interpreting-payload-data-from-the-sodaqone-universaltracker/374/9 

I passed an **other**  payload from an **unknown**  user to the python script:
`wsqDV/8nCidFHLMzFwW+AQQAMgQO` 
This payload decodes perfect.
I am stuck!
Please help :-)
Matthias

`pi@raspberrypi:~ $ echo $payload
poLJlK7MQNIpB+POeTdWS3ytJx+y
pi@raspberrypi:~ $ python ./sodaq_tracker_2.py $payload
Traceback (most recent call last):
  File "./sodaq_tracker_2.py", line 37, in <module>
    print (parse(arv[0]))
  File "./sodaq_tracker_2.py", line 18, in parse
    values["time"] = datetime.datetime.fromtimestamp(parsed[0])
ValueError: timestamp out of range for platform time_t`

`pi@raspberrypi:~ $ echo $payloadGood
wsqDV/8nCidFHLMzFwW+AQQAMgQO
pi@raspberrypi:~ $ python ./sodaq_tracker_2.py $payloadGood
{'sats': 4, 'temp': 39, 'course': 50, 'lon': 8.5406643, 'volt': 255, 'time': datetime.datetime(2016, 7, 11, 18, 35, 14), 'lat': 47.4294026, 'alt': 446, 'speed': 4, 'ttf': 14}
pi@raspberrypi:~ $`

**Comment by dslhias** [comment]
Sorry!
My fault.
I have everything set up from scratch and it works. :-)
Unfortunately, I do not know.
Best wishes
mateng
[closed]
